In [3]:
import pandas as pd
import csv
import requests
import json
from config import gkey

In [4]:
#read csv file into a pd data frame
csv_path = "Resources/zipcodes.csv"
zipcodes_original = pd.read_csv(csv_path, header=[0])

#preview data
zipcodes_original.head()

   Zip Code State         County           City  Time Zone  Distance
0     94103    CA  San Francisco  San Francisco          8         0
1     94119    CA  San Francisco  San Francisco          8         1
2     94120    CA  San Francisco  San Francisco          8         1
3     94125    CA  San Francisco  San Francisco          8         1
4     94126    CA  San Francisco  San Francisco          8         1

In [5]:
#Drop irrelevant columns
zipcodes_data = zipcodes_original[["Zip Code","County","City"]]

#preview data
zipcodes_data.head()

   Zip Code         County           City
0     94103  San Francisco  San Francisco
1     94119  San Francisco  San Francisco
2     94120  San Francisco  San Francisco
3     94125  San Francisco  San Francisco
4     94126  San Francisco  San Francisco

In [6]:
zipcodes_data.nunique()["City"]

112

In [7]:
sorted_zipcodes = zipcodes_data.groupby(["City"])
sorted_zipcodes.count()

                     Zip Code  County
City
Alameda                     2       2
Alamo                       1       1
Albany                      1       1
Alviso                      1       1
American Canyon             1       1
Antioch                     2       2
Atherton                    1       1
Belmont                     1       1
Belvedere Tiburon           1       1
Benicia                     1       1
Berkeley                   11      11
Birds Landing               1       1
Bolinas                     1       1
Boyes Hot Springs           1       1
Brentwood                   1       1
Brisbane                    1       1
Burlingame                  2       2
Canyon                      1       1
Castro Valley               2       2
Clayton                     1       1
Concord                     8       8
Corte Madera                2       2
Crockett                    1       1
Cupertino                   2       2
Daly City                   4       4
Danville                    2       2
Diablo                      1       1
Dublin                      1       1
El Cerrito                  1       1
El Granada                  1       1
...                       ...     ...
Rodeo                       1       1
Ross                        1       1
San Anselmo                 2       2
San Bruno                   1       1
San Carlos                  1       1
San Francisco              51      51
San Geronimo                1       1
San Gregorio                1       1
San Jose                    3       3
San Leandro                 3       3
San Lorenzo                 1       1
San Mateo                   5       5
San Pablo                   1       1
San Quentin                 2       2
San Rafael                  5       5
San Ramon                   2       2
Santa Clara                 7       7
Sausalito                   2       2
Sonoma                      1       1
South San Francisco         2       2
Stanford                    1       1
Stinson Beach               1       1
Suisun City                 1       1
Sunnyvale                   5       5
Sunol                       1       1
Union City                  1       1
Vallejo                     4       4
Vineburg                    1       1
Walnut Creek                4       4
Woodacre                    1       1

[112 rows x 2 columns]

In [11]:
#looked for nearby gas stations
#hard coded location lat and lng. still trying to figure out how to search with zipcode 
location = '37,-122'
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
radius = 2000
params = {"key":gkey,
         "location":"37,-122",
         "radius":radius,
          "type":"gas_station"
         }
query_url = f"{base_url}key={gkey}&location=37,-122&radius={radius}&rankby=prominence&type=gas_station"
query_url

'https://maps.googleapis.com/maps/api/place/nearbysearch/json?key=AIzaSyC3SfYMtCuAVDfvt_FycJcXcvEgdgD2tss&location=37,-122&radius=2000&rankby=prominence&type=gas_station'

In [9]:
response = requests.get(query_url).json()
response

{'html_attributions': [],
 'results': [{'geometry': {'location': {'lat': 36.985107, 'lng': -121.989512},
    'viewport': {'northeast': {'lat': 36.98646213029149,
      'lng': -121.9882439697085},
     'southwest': {'lat': 36.98376416970849, 'lng': -121.9909419302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
   'id': 'b435f935347a87e6c36a85a903625a12a3fa8dfc',
   'name': 'Shell',
   'photos': [{'height': 4032,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116583062108209279409/photos">Jerry Midland</a>'],
     'photo_reference': 'CmRaAAAAwaKbqkokWFMR2M-Fgc07gVyBjrok5wiCEj-_IkYL4rbCxmm2ajt-7hiXPwgz87qDG0YMaDUc-AnFdEzj1yfKjdVkXr6e9ESelU6gBTpR9VLb0c5y57tB0UGzjMOUtmdIEhDr5B4FbfAMAC5ID3iNNDjhGhQyOVERDy1IYVr3nqdCcWaHqodyLg',
     'width': 3024}],
   'place_id': 'ChIJZ2Ab5f4_joARRbtpihFM5nE',
   'plus_code': {'compound_code': 'X2P6+25 Live Oak, California, United States',
    'global_code': '848WX2P6+25'},
   'price_level': 2,
   'rating': 3.7,
   'reference': 'CmRRAAAAXavQA4xj_dsAiknV6zDLkiaLNu3TsSuplLmsMXG0-Ha3NaglkZEa29Bb9fbdMW_QocLmFyjUf5PvLDlALeZ49elq1EPi42dQqEWuJUeTqgeQb7UL5rWF-fRKqoMK__-tEhAbN9gzPZSgcxm2iVrY0StQGhTCkXNraA7EJdhd6hN-xZLDLeyYtQ',
   'scope': 'GOOGLE',
   'types': ['gas_station',
    'atm',
    'convenience_store',
    'car_wash',
    'finance',
    'store',
    'food',
    'point_of_interest',
    'establishment'],
   'vicinity': '2700 Soquel Avenue, Santa Cruz'},
  {'geometry': {'location': {'lat': 36.98783050000001, 'lng': -121.9846385},
    'viewport': {'northeast': {'lat': 36.9892827802915,
      'lng': -121.9833446197085},
     'southwest': {'lat': 36.9865848197085, 'lng': -121.9860425802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
   'id': 'd1d1b6509761fe2167ef50956249c7472a686087',
   'name': '76',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103513755301155812693/photos">Robin C. Benites</a>'],
     'photo_reference': 'CmRaAAAAeuVdfeSspAMW5PO_HyKuHoKVlPDo4QTUWS87V01tvC8EAXAYQmRYnhPHD-IW6TBVW-Gm0OujaV-B208AgL3CYnmhLTEY5_4lsSvRM2oTQuJOjKDBdKuVldvEG4zcxid9EhCh_mDfPVRpGYOnGQXfUI6kGhTz_Syx1V-N15Dzei-mxOFspJ79RQ',
     'width': 4032}],
   'place_id': 'ChIJVfsNf_w_joARe2qjjra7Pnw',
   'plus_code': {'compound_code': 'X2Q8+44 Live Oak, California, United States',
    'global_code': '848WX2Q8+44'},
   'price_level': 2,
   'rating': 3.8,
   'reference': 'CmRRAAAANm68-1IByZquLJC4I5OeVS5IjFQMuxTkSxwlYpVG-ZOla2Gbt3GcK0lG_FNVSc7Na_Dvv0XjBODberwlSBs2CECrHYjZyAruDuQd5dDXUyxeVooA7gNoOgZiG8r_4cXlEhAGQBks4kXs6P2gzS7ExywkGhTANaLmf_SxEmyJX8KE-Tzss6HB6g',
   'scope': 'GOOGLE',
   'types': ['gas_station', 'point_of_interest', 'establishment'],
   'vicinity': '1711, 1500 Soquel Drive, Santa Cruz'},
  {'geometry': {'location': {'lat': 36.9849884, 'lng': -121.989987},
    'viewport': {'northeast': {'lat': 36.9864367302915,
      'lng': -121.9885899197085},
     'southwest': {'lat': 36.98373876970851, 'lng': -121.9912878802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
   'id': '4bb2436beee6277ff774b73703f3d4339a7b746f',
   'name': 'Tesoro Petroleum',
   'place_id': 'ChIJwcPBH_8_joARFrtXBTDSOzw',
   'plus_code': {'compound_code': 'X2M6+X2 Live Oak, California, United States',
    'global_code': '848WX2M6+X2'},
   'rating': 3,
   'reference': 'CmRRAAAAcysuuLl7afONWjohe--vudtcjWYcky10TDZt2FxkvAF79yI-A9RjTYNE6QJkEICMl8Quwt6Hn0cbRkkzBnQARu0ufl5p8sF0zdw5pSxSc9fDIw8e2nXvhwpdpljYY6vyEhCLNIYebedjBXG8_XHYDiO1GhR-fysHWlre-II3x4PZaBgM-9uzZw',
   'scope': 'GOOGLE',
   'types': ['gas_station',
    'car_repair',
    'store',
    'food',
    'point_of_interest',
    'establishment'],
   'vicinity': '2680 Soquel Avenue, Santa Cruz'},
  {'geometry': {'location': {'lat': 36.9850054, 'lng': -121.9900109},
    'viewport': {'northeast': {'lat': 36.9864485302915,
      'lng': -121.9885728197085},
     'southwest': {'lat': 36.9837505697085, 'lng': -121.9912707802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/gas_station-71.png',
   'id': '83f52b73ae5efe8896570c8b30cc0be865e0b027',
   'name': 'Mobil',
   'opening_hours': {'open_now': True},
   'place_id': 'ChIJ04tDIP8_joARh8r8L6KSy9U',
   'plus_code': {'compound_code': 'X2P5+2X Live Oak, California, United States',
    'global_code': '848WX2P5+2X'},
   'rating': 3.8,
   'reference': 'CmRSAAAAA7yDFF20ZeCIhhtHMj4kKpDtRkSRVJl6gAD_oavvQCs_hREMVnqd9FtpR9mkFqSqbMi6iuRamMhAjTodlyH74xCbpWwovPLYOWMuFN1FrRFZa57T5AdLjSCJnkrYBH-UEhDJWuvTH9bV5q6lXswtirzUGhQ4OkmSeAmtcXNebJS7XSwL9f9GHQ',
   'scope': 'GOOGLE',
   'types': ['gas_station', 'point_of_interest', 'establishment'],
   'vicinity': '2680 Soquel Avenue, Santa Cruz'}],
 'status': 'OK'}

In [10]:
target_cities = ["San Francisco","Sausalito","Novato"]